project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - about.qmd
    - projects.qmd
    - "projects/*.qmd"
    - blog/index.qmd
    - "blog/posts/*.qmd"
    - "bibliography/*.qmd"

website:
  title: "Zach Rivers, PharmD, PhD"
  site-url: https://riverspharmd.github.io/ztr_website/
  sidebar:
    style: docked
    search: true
    background: light
    border: false
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Publications"
        href: bibliography/published_works.qmd
  page-navigation: false
  page-footer:
    left: Copyright 2025
    right: Made with Quarto

format:
  html:
    theme:
      dark: slate
      light: cosmo
    respect-user-color-scheme: true
    toc: true
    code-fold: true
    highlight-style: github
    css: styles.css
    bibliography: references.bib
    citation-link: true
    link-citations: true

execute:
  freeze: auto