project:
  type: website
  output-dir: _site

website:
  title: "Zach's Personal Website"
  site-url: https://riverspharmd.github.io/ztr_website/
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Blog"
        file: blog/index.qmd
      - text: "Publications"
        file: bibliography/published_works.qmd
  page-navigation: true
  page-footer:
    left: Copyright 2025
    right: Made with Quarto
  search:
    location: navbar
    type: overlay

format:
  html:
    theme:
      dark: slate
      light: cosmo
    respect-user-color-scheme: true
    toc: true
    code-fold: true
    highlight-style: github
    css: styles.css
    bibliography: references.bib
    citation-link: true
    link-citations: true

execute:
  freeze: auto