---
title: Published Works
author: Zach Rivers, PharmD, PhD
date: 2025-04-01
format:
    html:
        embed-resources: true
        toc: false
---

# Purpose
This document collects and organizes my published work by topic and skillset. Most code is found in private github repositories, but where open code is available, it can be found [here](https://github.com/RiversPharmD) with specific callouts found throughout this document.

# Real-World Data

## Tempus AI
* @aggarwal2023assessment

This manuscript used real world data to understand how a biomarker based test predicted cancer outcomes across a diverse patient population. I was responsible for clinical chart review and data analysis.

* @rivers2023molecular

This project attempted to identify the origin of cancers of unknown primary using biomarkers. I developed an analytic data pipeline to combine claims, EHR, and curated patient data with genetic test results to understand how clinicians used the test results to drive patient care.

* @maddalena2024impact

This project used claims data linked to genetic test results to replicate clinical trial findings in real world data. I supported this project through data pipeline design and served as an analytic advisor and claims subject matter expert.

* @gentzler2024dynamic

This manuscript links clinical and genetic real-world data to imaging response data. I supported this analysis as an oncology pharmacotherapy subject-matter expert.

* @rivers2024pp01

This poster explored how real-world outcomes were impacted by patient-reported race and ethnicity. This allowed me to use propensity score matching and account for time bias in the survival analyses. I designed the project, and conducted the analysis in R.

## Fred Hutchinson Cancer Research Center
* @khor2023association

This poster used a novel data linkage between a cancer registry, claims data, and bankruptcy data to explore how patients diagnosed with screenable cancers were impacted by their pre-diagnosis financial toxicity. I was responsible for early study design and theoretical framework.

## University of Minnesota
* @willis2022real

Clinical research study using EHR abstracted data to understand the impact of a cancer biomarker on real-world overall survival. I was responsible for data analysis and result reporting, including design and production of waterfall plots in R.

* @rivers2022pgx

Part of my dissertation, this manuscript used real-world data to identify treatment patterns and parameters for an economic model.

* @nguyen2020pharmacogenomics

Clinical research study using EHR data linked to patient samples. Served as an analytic mentor and advisor to early PhD students leading research.

* @kessel2020identification

Exploratory study examining the impact and role of biomarkers in kidney cancer. I was responsible for data analysis and review.

* @ramsey2020

This manuscript was a multi-stakeholder project where I served as one of the points of contact for an individual research institution. This project gave me the opportunity to work as a consultant as part of a larger data project.

# Economic Modeling

## Tempus AI
* @rivers2024cost

This poster, with a manuscript forthcoming, uses real-world claims, EHR, and genetic testing information (from [@gentzler2024dynamic]) to understand the clinical and economic impact of biomarker testing in a pan-cancer population treated with immunotherapy. I built the data pipeline, wrote the simulation model in R, and was responsible for this project to our internal and external stakeholders.

## Fred Hutchinson Cancer Research Center
* @rivers2022ee97

This abstract looked at how economic analyses of polygenic risk scores included, or didn't include, population level data. This was intended to support a K Award application, but I was recruited away to industry.

* @rivers2023translating

This manuscript used an Excel-based model to provide stakeholders with a tool to understand the economic impact of different cancer survivorship interventions. I updated and refined the model, and worked with focus groups to understand use cases.


## University of Minnesota

### Dissertation work [@rivers2021personalizing]
* @rivers2020cost and @rivers20204106

These abstracts present the early and middle stages of an economic model of genetic testing in a US population over a lifetime time horizon. Built in TreeAge, and subsequently ported to R.

* @rivers2020pcn109 

This abstract is a budget impact model of implementing the above genetic testing from the perspective of a US Cancer Center.

* @rivers2021optimizing

This abstract conducts a value of information analysis (VOI) for the economic model of genetic testing in colorectal cancer.

### Others
* @biltaji2021can

This manuscript looked at the potential for biomarkers to inform colorectal cancer prevention. A complex economic model was constructed in TreeAge, and I was responsible for updates, data changes, and final model outputs.

* @rivers2018preventing

This model used real-world genetic variant data and treatment patterns to explore how biomarker testing could prevent nausea and vomiting in cancer.

* @kumar2021pns15

This model explored pharmacogenomic testing in pediatric patients. I supported model design and programming.

# Survey Panels and Qualitative Work

## Tempus AI

* @rivers2023exploring

I led a group of clinicians and researchers at Tempus in identifying how a new clinical trial program could benefit pediatric cancer patients. I developed the survey instrument and was responsible for data analysis and publication.

## Fred Hutchinson Cancer Research Center
* @rivers2022differences and @rivers2022discordance

This project used patient-reported survey data to understand how patients and their caregivers experienced and perceived financial toxicity. I was responsible for data analysis and result preparation. [GitHub Repo](https://github.com/RiversPharmD/AZFinTox)


## University of Minnesota

* @lounsbery2019tracked

Manuscript exploring how pharmacy students rated their confidence and education during their clinical rotations. Responsible for analytics and result presentation.

# Pharmaceutical Care and Practice

## University of Minnesota

* @coles2015use

Early publication from my PharmD, collaboration between benchtop scientists and clinicians to understand pharmacokinetics of a novel antiepileptic formulation.

* @rivers2018romidepsin

Case report and literature review based on clinical rotation experience. A complex patient case led me to explore a potential underreported adverse event signal in a class of anticancer agents.

* @fikru2016coverage

This abstract compared and contrasted pharmacogenomics coverage by insurance companies. This project showed me that there was a gap in the economic field around genetic testing and biomarkers

* @rivers2016kava

PharmD Capstone paper. Reviewed mechanisms of a plant-based approach to the management of anxiety.
